//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miunie.ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConsoleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConsoleStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miunie.ConsoleApp.ConsoleStrings", typeof(ConsoleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue....
        /// </summary>
        internal static string ANY_KEY_TO_CONTINUE {
            get {
                return ResourceManager.GetString("ANY_KEY_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /!\ Miunie is not currently running....
        /// </summary>
        internal static string BOT_IS_NOT_RUNNING {
            get {
                return ResourceManager.GetString("BOT_IS_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =) Miunie is running....
        /// </summary>
        internal static string BOT_IS_RUNNING {
            get {
                return ResourceManager.GetString("BOT_IS_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Error:
        ///The configuration could not retrieve the item:&apos;{0}&apos;
        ///Enter your desired value: (or type EXIT).
        /// </summary>
        internal static string CONFIG_ERROR {
            get {
                return ResourceManager.GetString("CONFIG_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Discord bot&apos;s token: .
        /// </summary>
        internal static string ENTER_TOKEN {
            get {
                return ResourceManager.GetString("ENTER_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number. Don&apos;t type in the [ and ] characters. Just the number..
        /// </summary>
        internal static string ERROR_CHOICE_NOT_A_NUMBER {
            get {
                return ResourceManager.GetString("ERROR_CHOICE_NOT_A_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miunie is in the headless mode. The UI will not render for the lifetime of this application..
        /// </summary>
        internal static string HEADLESS_STARTED {
            get {
                return ResourceManager.GetString("HEADLESS_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered the following token, is it correct? (ignore the double quotes)
        ///&quot;{0}&quot;.
        /// </summary>
        internal static string IS_TOKEN_CORRECT {
            get {
                return ResourceManager.GetString("IS_TOKEN_CORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1] Edit bot configuration
        ///[2] Start/Stop Miunie
        ///[3] Stop Miunie &amp; Exit.
        /// </summary>
        internal static string MAIN_MENU_OPTIONS {
            get {
                return ResourceManager.GetString("MAIN_MENU_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    __  __ _             _      
        ///   |  \/  (_)           (_)     
        ///   | \  / |_ _   _ _ __  _  ___ 
        ///   | |\/| | | | | | &apos;_ \| |/ _ \
        ///   | |  | | | |_| | | | | |  __/
        ///   |_|  |_|_|\__,_|_| |_|_|\___|
        ///
        ///              The community-made Discord bot.
        /// </summary>
        internal static string MIUNIE_ASCII_HEADER {
            get {
                return ResourceManager.GetString("MIUNIE_ASCII_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miunie has been started..
        /// </summary>
        internal static string MIUNIE_STARTED {
            get {
                return ResourceManager.GetString("MIUNIE_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enter headless mode without Miunie running....
        /// </summary>
        internal static string NO_HEADLESS_WITHOUT_RUNNING {
            get {
                return ResourceManager.GetString("NO_HEADLESS_WITHOUT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an action by typing its number: .
        /// </summary>
        internal static string PLEASE_ENTER_MENU_NUMBER {
            get {
                return ResourceManager.GetString("PLEASE_ENTER_MENU_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s try {0}. I have a good feeling about this one..
        /// </summary>
        internal static string RANDOM_TOKEN_MESSAGE {
            get {
                return ResourceManager.GetString("RANDOM_TOKEN_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your choice was not recognized as an option in the menu. Please try again..
        /// </summary>
        internal static string UNKNOWN_OPTION_SELECTED {
            get {
                return ResourceManager.GetString("UNKNOWN_OPTION_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to press either [Y] or [N].
        /// </summary>
        internal static string YES_NO_PROMPT {
            get {
                return ResourceManager.GetString("YES_NO_PROMPT", resourceCulture);
            }
        }
    }
}
