namespace Miunie.Core
{
    public enum PhraseKey
    {
        REPUTATION_GIVEN,
        REPUTATION_TAKEN,
        CANNOT_SELF_REP,
        USER_EMBED_TITLE,
        USER_EMBED_NAME_TITLE,
        USER_EMBED_IS_BOT,
        USER_EMBED_IS_HUMAN,
        USER_EMBED_REALNESS_TITLE,
        USER_EMBED_REP_TITLE,
        USER_EMBED_ROLES_TITLE,
        USER_EMBED_JOINED_AT_TITLE,
        GUILD_EMBED_TITLE,
        GUILD_EMBED_NAME_TITLE,
        GUILD_EMBED_STATS_TITLE,
        GUILD_EMBED_ROLES_TITLE,
        GUILD_EMBED_CREATED_AT_TITLE
    }
}
