namespace Miunie.Core
{
    public enum PhraseKey
    {
        REPUTATION_GIVEN,
        REPUTATION_TAKEN,
        CANNOT_SELF_REP,
        SHOW_REMOTE_REPO,
        USER_EMBED_TITLE,
        USER_EMBED_NAME_TITLE,
        USER_EMBED_IS_BOT,
        USER_EMBED_IS_HUMAN,
        USER_EMBED_REALNESS_TITLE,
        USER_EMBED_REP_TITLE,
        USER_EMBED_REP_LOG_TITLE,
        USER_EMBED_REP_LOG_EMPTY,
        USER_EMBED_ROLES_TITLE,
        USER_EMBED_JOINED_AT_TITLE,
        USER_EMBED_CREATED_AT_TITLE,
        GUILD_EMBED_TITLE,
        GUILD_EMBED_NAME_TITLE,
        GUILD_EMBED_STATS_TITLE,
        GUILD_EMBED_ROLES_TITLE,
        GUILD_EMBED_CREATED_AT_TITLE,
        TIME_NO_TIMEZONE_INFO,
        TIME_TIMEZONE_INFO,
        TIME_NEW_OFFSET_SET,
        USER_EMBED_TIME_TITLE,
        USER_EMBED_TIME_NOSET,
        USER_EMBED_TIME,
        YES_NO_MAYBE,
        TIME_USERTIME_FROM_LOCAL,
        TIME_NO_MESSAGE,
        TIME_MESSAGE_INFO_EDIT,
        TIME_MESSAGE_INFO_NO_EDIT
    }
}

