//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miunie.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Miunie.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry {0}, you cannot influence your own reputation! Try influencing other people instead. :smirk:{{OR}}
        ///Aww, {0}... I can&apos;t do that. If you need your reputation to change, try blackmailing others to do it for you.{{OR}}
        ///Hey {0}, did you really think you could influence yourself? Get some friends to do that for you.{{OR}}
        ///Did {0} just try to influence someone that isn&apos;t me?! Wait, they tried to self-rep? Hah!.
        /// </summary>
        public static string CANNOT_SELF_REP {
            get {
                return ResourceManager.GetString("CANNOT_SELF_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :calendar: Creation date.
        /// </summary>
        public static string GUILD_EMBED_CREATED_AT_TITLE {
            get {
                return ResourceManager.GetString("GUILD_EMBED_CREATED_AT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string GUILD_EMBED_NAME_TITLE {
            get {
                return ResourceManager.GetString("GUILD_EMBED_NAME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string GUILD_EMBED_ROLES_TITLE {
            get {
                return ResourceManager.GetString("GUILD_EMBED_ROLES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server stats.
        /// </summary>
        public static string GUILD_EMBED_STATS_TITLE {
            get {
                return ResourceManager.GetString("GUILD_EMBED_STATS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **ABOUT THIS SERVER**.
        /// </summary>
        public static string GUILD_EMBED_TITLE {
            get {
                return ResourceManager.GetString("GUILD_EMBED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You better start making sense with other than &apos;{0}&apos;{{OR}}
        ///Come again, I don&apos;t understand &apos;{0}&apos;{{OR}}
        ///Let&apos;s try that one more time and try something different than &apos;{0}&apos;{{OR}}
        ///What does &apos;{0}&apos; mean here?.
        /// </summary>
        public static string INCORRECT_VERB {
            get {
                return ResourceManager.GetString("INCORRECT_VERB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** just got reputation from {1}! :trophy:{{OR}}
        ///**{0}** just got reputation from {1}! :fireworks:{{OR}}
        ///**{0}** just got reputation from {1}! :tada:{{OR}}
        ///**{0}** was given some reputation by {1}! What&apos;s in it for me, though? :thinking:.
        /// </summary>
        public static string REPUTATION_GIVEN {
            get {
                return ResourceManager.GetString("REPUTATION_GIVEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **{0}** just had reputation removed from {1} :({{OR}}
        ///**{0}** just had reputation removed from {1} :&apos;({{OR}}
        ///**{0}** just had reputation removed from {1} :sob:.
        /// </summary>
        public static string REPUTATION_TAKEN {
            get {
                return ResourceManager.GetString("REPUTATION_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find my source code on GitHub:
        ///https://github.com/discord-bot-tutorial/Miunie.
        /// </summary>
        public static string SHOW_REMOTE_REPO {
            get {
                return ResourceManager.GetString("SHOW_REMOTE_REPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh yeah, message {0} was created {1} but was also edited on {2}{{OR}}
        ///{1} was when {0} was created, but it was edited {2}.
        /// </summary>
        public static string TIME_MESSAGE_INFO_EDIT {
            get {
                return ResourceManager.GetString("TIME_MESSAGE_INFO_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found it! {0} was first seen {1}{{OR}}
        ///Sneaky, sneaky, {0} was first spotted {1}{{OR}}
        ///{0} was launched {1}.
        /// </summary>
        public static string TIME_MESSAGE_INFO_NO_EDIT {
            get {
                return ResourceManager.GetString("TIME_MESSAGE_INFO_NO_EDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! Your current time was stored!{{OR}}
        ///Alright, I&apos;ll remember your time.{{OR}}
        ///Cool, if someone asks, this meeting didn&apos;t happen. (but I&apos;ll totally remember what time it is for you).
        /// </summary>
        public static string TIME_NEW_OFFSET_SET {
            get {
                return ResourceManager.GetString("TIME_NEW_OFFSET_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! {0}&apos;s current time was stored!{{OR}}
        ///Alright, I&apos;ll remember {0}&apos;s time.{{OR}}
        ///Cool, if someone asks, this meeting didn&apos;t happen. (but I&apos;ll totally remember what time it is for {0}).
        /// </summary>
        public static string TIME_NEW_OFFSET_SET_ADMIN {
            get {
                return ResourceManager.GetString("TIME_NEW_OFFSET_SET_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nope! Nobody by that name here{{OR}}
        ///I asked everyone, but nobody knows...{{OR}}
        ///Sorry, couldn&apos;t find what you are looking for!.
        /// </summary>
        public static string TIME_NO_MESSAGE_INFO {
            get {
                return ResourceManager.GetString("TIME_NO_MESSAGE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :question: I have no idea what time it is for {0}.{{OR}}
        ///:question: {0} is one of **THOSE** people. They don&apos;t have their time set..
        /// </summary>
        public static string TIME_NO_TIMEZONE_INFO {
            get {
                return ResourceManager.GetString("TIME_NO_TIMEZONE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :clock1: For {0} it&apos;s currently {1:HH:mm}{{OR}}
        ///:clock1: It&apos;s currently {1:HH:mm} where {0} is at.{{OR}}
        ///:clock1: Believe it or not, it&apos;s {1:HH:mm} right now in {0} land.{{OR}}
        ///:clock1: Time flies, but not so much for {0}, &apos;cause for them it&apos;s {1:HH:mm}..
        /// </summary>
        public static string TIME_TIMEZONE_INFO {
            get {
                return ResourceManager.GetString("TIME_TIMEZONE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome it&apos;s {0:HH:mm} for you and {2:HH:mm} for {1}{{OR}}
        ///Far out it&apos;s {0:HH:mm} locally and {2:HH:mm} where {1} is at!{{OR}}
        ///No way it&apos;s {0:HH:mm} and for {1} it&apos;s {2:HH:mm}{{OR}}
        ///{0:HH:mm} somewhere but for {1} it&apos;s {2:HH:mm}{{OR}}
        ///It&apos;s {2:HH:mm} at {1}&apos;s house, when it&apos;s {0:HH:mm} for you!.
        /// </summary>
        public static string TIME_USERTIME_FROM_LOCAL {
            get {
                return ResourceManager.GetString("TIME_USERTIME_FROM_LOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will be {1:HH:mm} for {0} in {2} {3}{{OR}}
        ///In {2} {3} it&apos;s {1:HH:mm} at {0}&apos;s house!{{OR}}
        ///{1:HH:mm} in {0} land in about {2} {3}.
        /// </summary>
        public static string TIME_USERTIME_IN_FUTURE {
            get {
                return ResourceManager.GetString("TIME_USERTIME_IN_FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t understand what in {0} {1} means{{OR}}
        ///Me no understand {0} {1}!{{OR}}
        ///What are you trying to say with {0} {1}.
        /// </summary>
        public static string TIME_USERTIME_IN_FUTURE_UNPARSABLE {
            get {
                return ResourceManager.GetString("TIME_USERTIME_IN_FUTURE_UNPARSABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :calendar_spiral: Creation date.
        /// </summary>
        public static string USER_EMBED_CREATED_AT_TITLE {
            get {
                return ResourceManager.GetString("USER_EMBED_CREATED_AT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _A software person._{{OR}}
        ///_A bot._ :robot:{{OR}}
        ///_Soon to be our AI overlord._.
        /// </summary>
        public static string USER_EMBED_IS_BOT {
            get {
                return ResourceManager.GetString("USER_EMBED_IS_BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Passes ReCaptcha,
        ///so I guess they&apos;re real._{{OR}}
        ///_A real human being._{{OR}}
        ///_Real flesh, bones,
        ///blood, all that._.
        /// </summary>
        public static string USER_EMBED_IS_HUMAN {
            get {
                return ResourceManager.GetString("USER_EMBED_IS_HUMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :calendar: Joined.
        /// </summary>
        public static string USER_EMBED_JOINED_AT_TITLE {
            get {
                return ResourceManager.GetString("USER_EMBED_JOINED_AT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :label: Name.
        /// </summary>
        public static string USER_EMBED_NAME_TITLE {
            get {
                return ResourceManager.GetString("USER_EMBED_NAME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :electric_plug: Bot or not{{OR}}
        ///:electric_plug: Human/Bot.
        /// </summary>
        public static string USER_EMBED_REALNESS_TITLE {
            get {
                return ResourceManager.GetString("USER_EMBED_REALNESS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation? What&apos;s that?{{OR}}
        ///I don&apos;t see any reputation here...{{OR}}
        ///I&apos;ve caught you empty-repped!.
        /// </summary>
        public static string USER_EMBED_REP_LOG_EMPTY {
            get {
                return ResourceManager.GetString("USER_EMBED_REP_LOG_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **REPUTATION LOG**.
        /// </summary>
        public static string USER_EMBED_REP_LOG_TITLE {
            get {
                return ResourceManager.GetString("USER_EMBED_REP_LOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :fleur_de_lis: Reputation.
        /// </summary>
        public static string USER_EMBED_REP_TITLE {
            get {
                return ResourceManager.GetString("USER_EMBED_REP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :dolls: Roles.
        /// </summary>
        public static string USER_EMBED_ROLES_TITLE {
            get {
                return ResourceManager.GetString("USER_EMBED_ROLES_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s currently {0:HH:mm} over there :){{OR}}
        ///Their clock shows {0:HH:mm} right now..
        /// </summary>
        public static string USER_EMBED_TIME {
            get {
                return ResourceManager.GetString("USER_EMBED_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have no idea what time it is for them.{{OR}}
        ///No time set :cry:{{OR}}
        ///Twelve... ten... -ish... Yeah I have no idea..
        /// </summary>
        public static string USER_EMBED_TIME_NOSET {
            get {
                return ResourceManager.GetString("USER_EMBED_TIME_NOSET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :clock4: Local time.
        /// </summary>
        public static string USER_EMBED_TIME_TITLE {
            get {
                return ResourceManager.GetString("USER_EMBED_TIME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **YOUR AWESOME PROFILE**{{OR}}
        ///**YOUR COOL PROFILE**{{OR}}
        ///**YOUR MAGNIFICENT PROFILE**{{OR}}
        ///**YOUR DANK PROFILE**.
        /// </summary>
        public static string USER_EMBED_TITLE {
            get {
                return ResourceManager.GetString("USER_EMBED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chances are good{{OR}}
        ///No looking good{{OR}}
        ///Try again later.
        /// </summary>
        public static string YES_NO_MAYBE {
            get {
                return ResourceManager.GetString("YES_NO_MAYBE", resourceCulture);
            }
        }
    }
}
